name: Deploy to GH Pages
on:
    push:
        branches: [ main, master ]
    pull_request:
        branches: [ main, master ]
jobs:
    build:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
        - name: Deploy React to GitHub Pages
          uses: bitovi/github-actions-react-to-github-pages@v1.2.4
        